---
AWSTemplateFormatVersion: "2010-09-09"
Description: Template for DevOps Girls Workshop 2023
Parameters:
  SecurityGroupName:
    Description: EC2 Security Group Name
    Type: String
  KeyName:
    Description: EC2 KeyPair Name
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair
    Default: devops-girls-2023
  HostedZoneId:
    Description: Route 53 Hosted Zone Id
    Type: String
  DomainName:
    Description: Route 53 Fully Qualified Domain Name
    Type: String
Resources:
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      # TODO: Add properties according to the playbook
      IamInstanceProfile: !Ref InstanceProfile
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          amazon-linux-extras install nginx1 -y
          systemctl enable --now nginx
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub ${AWS::StackName}-profile
      Path: /
      Roles:
        - EC2-AssumeRoleWithEC2ForDevopsGirls2023
  EIP:
    Type: AWS::EC2::EIP
  EIPAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      EIP: !Ref EIP
      InstanceId: !Ref Instance
  # TODO: Add RecordSet
